name: test_rx
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

  #Rx
  rxdart: ^0.23.1
  rx_command: ^5.0.1
  rx_widgets: ^3.0.0

  #DI
  provider: ^4.0.0-dev
  get_it: ^4.0.2
  injectable: ^0.4.0+1

  #Networking
  dio: ^3.0.7

  #BuiltValue
  built_value: ^7.0.0
  built_collection: ^4.3.0

  #routing
  auto_route: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  #DI
  injectable_generator: ^0.4.1

  build_runner: ^1.7.2

  #route generator
  auto_route_generator: ^0.5.0

  #BuiltValue
  built_value_generator: ^7.0.0

  #Linter
  pedantic: ^1.9.0

flutter:
  uses-material-design: true